### PR TITLE
Enhance groovy-html.template

### PR DESCRIPTION
**Pull request by KostyaSha**

### CODE REVIEW

**Comment by slide** [comment]
Should this still be open? Is it still being worked on?

**Comment by KostyaSha** [comment]
I switched to other issues. But i think this changes are still valid.

**Comment by slide** [comment]
So, it's not a work in progress anymore?

**Comment by KostyaSha** [comment]
@slide i think this portion of changes was completed. I also did some other improvements but forgot send. 
If you are ok with this changes, then please merge.

**Pull request merged**
