### PR TITLE
Styling changes + change in test results table + code alignment

### PR DESCRIPTION
**Pull request by rdagum**
Sample of success:
image

Sample of failure:
image

### CODE REVIEW

**Comment by davidvanlaatum** [comment]
Would also have been nice to include a before image just so I didn't have to go hunting to figure out what it looked like before ;)

**Comment by davidvanlaatum** [comment]
Also please include a third color for unstable

**Comment by rdagum** [comment]
I updated to use same styling in artifacts and maven artifacts. However, I couldn't test the maven artifacts output because I don't have a project that uses that.
I added the test age as well.

**Comment by davidvanlaatum** [comment]
Just for your own info http://github.com/jglick/simple-maven-project-with-tests

**Pull request merged**
