### PR TITLE
feat: Use credentials plugin for managing authentication credentials

### PR DESCRIPTION
**Pull request by slide**
This switches the MailAccount class to use credentials instead of directly storing the username/password. There is an upgrade path from the old settings to using credentials.

https://issues.jenkins.io/browse/JENKINS-66849

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Hacktoberfest submission

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Comment by slide** [comment]
Thanks!

**Comment by basil** [comment]
Released in [2.85](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.85).

**Comment by MarcusUA** [comment]
This change has introduced strange behavior, it migrated creds to Global Credentials (login is correct for sure), but it fails to use them, and uses root with no password:

> DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
> DEBUG SMTP: need username and password for authentication
> DEBUG SMTP: protocolConnect returning false, host=smtp.office365.com, user=root, password=<null>
> DEBUG SMTP: useEhlo true, useAuth true
> DEBUG SMTP: trying to connect to host "smtp.office365.com", port 587, isSSL false

After I created new creds entry with correct user, it started to work, but still acting strange:
> Sending email to: redacted@redacted.com
> DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
> DEBUG SMTP: need username and password for authentication
> DEBUG SMTP: protocolConnect returning false, host=smtp.office365.com, user=root, password=<null>
> DEBUG SMTP: useEhlo true, useAuth true
> DEBUG SMTP: trying to connect to host "smtp.office365.com", port 587, isSSL false

but few lines later is same log:

> DEBUG SMTP: protocolConnect login, host=smtp.office365.com, user=redacted@redacted.com, password=<non-null>
> DEBUG SMTP: Attempt to authenticate using mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM XOAUTH2 
> DEBUG SMTP: Using mechanism LOGIN
> DEBUG SMTP: AUTH LOGIN command trace suppressed
> DEBUG SMTP: AUTH LOGIN succeeded

**Comment by slide** [comment]
Can you submit an issue and attach your config.xml for the emailext plugin (make sure to remove any sensitive info).

**Comment by MCMicS** [comment]
Also have same issue after Update plugin.
I've create an issue and try to reproduce it again on other machine

https://issues.jenkins.io/browse/JENKINS-67220

**Comment by slide** [comment]
Just to clarify, you had existing username/password stored for your connection, you upgraded the plugin and restarted Jenkins and then started a build and the creds were wrong?

**Comment by MCMicS** [comment]
Yes i had valid credentials. After update it was migrated to credentials. After restart the serve and started a build no mail was sent

**Comment by matthiasklein** [comment]
Also have the same problem after updating the plugin.

I had to create the credentials again to make them work. The automatically converted ones did not work.

**Comment by cfischer-oo-software** [comment]
Is there any solution or workaround available? 

Using 2.85. Rollback to 2.84 results in other errors when sending email.

I'm reading "had to create the credentials again to make them work", but: In the Jenkins System Configuration ("E-mail Notification") I can enter username/password only, a cannot assign any saved credential. Re-entering username/password does not change anything. The log of a simple freestyle test job sending an email shows:

10:53:26 DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
10:53:26 DEBUG SMTP: need username and password for authentication
10:53:26 DEBUG SMTP: protocolConnect returning false, host=<the-servername>, user=<not the value specified in system configuration>, password=<null>

Any help is greatly appreciated.

**Comment by arnisjuraga** [comment]
@cfischer-oo-software did you resolve this issue?
I have exactly the same problem. using version 2.88.

Now I am upgrading to 2.89 to see if it helps.

**Pull request merged**
