### PR TITLE
[Fix JENKINS-37995] X failure trigger

### PR DESCRIPTION
**Pull request by KostyaSha**
https://issues.jenkins-ci.org/browse/JENKINS-37995

### CODE REVIEW

**Comment by KostyaSha** [comment]
@davidvanlaatum please review

**Comment by KostyaSha** [comment]
Thanks!

**Comment by KostyaSha** [comment]
Found bug in UI getter :(

**Comment by KostyaSha** [comment]
Fix with test case https://github.com/jenkinsci/email-ext-plugin/pull/143

**Comment by Planet2010** [comment]
any groovy dsl support with x failure?

**Comment by davidvanlaatum** [comment]
no

**Pull request merged**
