### PR TITLE
enable setter for smtpHost in descriptor

### PR DESCRIPTION
**Pull request by keinkonzept**

### CODE REVIEW

**Comment by davidvanlaatum** [comment]
Is this fixing a bug or adding for feature?

**Comment by keinkonzept** [comment]
It's adding for a new feature. Basic e-mail notifier has this setter, along with setDefaultSuffix. It's needed to configure plugin programatically without overhead of submitting whole configuration JSON.

**Comment by sgtcoolguy** [comment]
It'd be nice to have setters for **all** the properties, so that I could programmatically set up the plugin using groovy scripts. I use chef to configure our Jenkins master. I can write out overridden plugin config XML files to disk, but that can be a pain when hey contain values needing to be encrypted - plus I seem t need to restart Jenkins to get the values reflected, a simple reload config from disk doesn't cut it.

But using groovy to manipulate the plugins in code does work without a restart, and avoids needing to jump through hoops to encrypt the secret values before sticking them into the xml file - it's just that not all plugins expose an API to be able to configure them outside the web UI.

**Comment by davidvanlaatum** [comment]
Create a issue in Jira and I'll do it at some stage

**Comment by sgtcoolguy** [comment]
Awesome, thanks: https://issues.jenkins-ci.org/browse/JENKINS-39147

**Pull request merged**
