### PR TITLE
Java11 readiness

### PR DESCRIPTION
**Pull request by oleg-nenashev**
#180 and #179 , just another attempt to confuse CI even more

### CODE REVIEW

**Comment by batmat** [comment]
Perfect, this time failures seem real. Looking. Thanks!

**Comment by batmat** [comment]
Superseded by https://github.com/jenkinsci/email-ext-plugin/pull/183 ...

Getting there :) phew

**Comment by batmat** [comment]
@oleg-nenashev you can close this one now. I'm following up in #183. Thanks!

**Comment by slide** [comment]
We can use this pr to integrate from the java11-readiness branch

**Comment by batmat** [comment]
@slide you are totally right.

**Comment by batmat** [comment]
So much green, I was getting not so much used to it :-)

**Comment by batmat** [comment]
@slide if you can consider releasing, even an experimental release, that would be awesome. Thanks a lot!

**Comment by slide** [comment]
@batmat I am working on a release.

**Pull request merged**
