### PR TITLE
Remove integration with Static Analysis Utilities plugin

### PR DESCRIPTION
**Pull request by basil**
See [JENKINS-55744](https://issues.jenkins.io/browse/JENKINS-55744).

I first announced in [the release notes for 2.78](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.78) that integration with the [Static Analysis Utilities](https://github.com/jenkinsci/analysis-core-plugin) plugin was deprecated in the Email Extension plugin and would be removed in a future release. I posted the same [deprecation warning](https://issues.jenkins.io/browse/JENKINS-55744?focusedCommentId=400413&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-400413) in the corresponding Jira issue. I also updated the email template for this feature to include the same warning, mentioning the Jira issue. This last notification would be hard to miss, since all users who use this feature would begin seeing the warning in emails (regardless of whether or not they read Jenkins plugin release notes or Jira issues).

Furthermore, in [the release notes for 2.81](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.81), I explicitly confirmed that integration with the Static Analysis Utilities plugin would be removed in the first quarter of 2021, regardless of whether or not anyone submits a pull request to add integration with the [Warnings Next Generation](https://plugins.jenkins.io/warnings-ng/) plugin. I posted the same [removal warning](https://issues.jenkins.io/browse/JENKINS-55744?focusedCommentId=402823&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-402823) in the corresponding Jira issue.

It has now been about 4 months since this integration was deprecated, and I have received neither any pull requests to add integration with the Warnings Next Generation plugin nor any pleas from users to retain this deprecated feature. Therefore, as promised, I am going ahead with the removal of integration with the Static Analysis Utilities plugin.

### CODE REVIEW

**Comment by uhafner** [comment]
Seems that no one is using emails nowadays. Since the analysis suite will be removed from the update center it makes sense to remove the template as well.

**Review by uhafner — APPROVED** [review]

**Comment by timja** [comment]
Could this be released, see https://github.com/jenkinsci/plugin-installation-manager-tool/issues/294

**Comment by basil** [comment]
Thanks for pointing this out, @darxriggs and @timja. I will do a release of Email Extension sometime this week.

**Comment by basil** [comment]
Released in [2.82](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.82).

**Pull request merged**
