### PR TITLE
change ListRecipientProvider for pipeline code

### PR DESCRIPTION
**Pull request by qxo**
change ListRecipientProvider for pipeline code

eg:

```
node {
 emailext (
     // attachmentsPattern: '**',
      subject: subject,
      body: details,
      recipientProviders: [
          [$class: 'ListRecipientProvider', recipientList: "${emailList}"]
      ]
   );

}
```

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Makes sense to at least declare the `@Symbolz`to avoid the `$class` definition. 

* I'm not sure this approach is completely safe for AbstractProjects
* Snippet Generator will unlikely work with  such approach (maybe I'm wrong)

**Comment by qxo** [comment]
@oleg-nenashev 
The code work for me in jenkins pipeline.
I have no time to check other use case
You may modify the code for other use case  :)

**Comment by davidvanlaatum** [comment]
I don't understand why this is needed? You can just pass the emails into the emailext command directly eg
```
node {
 emailext (
     // attachmentsPattern: '**',
      subject: subject,
      body: details,
      to: "${emailList}"
   );
}
```

**Comment by qxo** [comment]
@davidvanlaatum  on my test  "to" argument not work:)

**Comment by davidvanlaatum** [comment]
OK log an issue at http://issues.jenkins-ci.org

**Pull request closed without merging**
