### PR TITLE
Factor out Jackson version into a property

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Review by jglick — COMMENTED** [review]
We cannot use the API plugin here?

**Comment by basil** [comment]
> We cannot use the API plugin here?

I see no reason why we can't use the API plugin. Is that recommended over directly depending on Jackson?

**Comment by jglick** [comment]
As a rule, yes.

**Comment by basil** [comment]
I tried it out and found that the first version of `jackson2-api` that works is 2.11.1, which is a bit recent (June 29, 2020). I want to do at least one release of this plugin with older minimum plugin requirements before I start increasing the minimum Jenkins version and minimum plugin requirements, so I think I'll keep the status quo for now and merge that change after the next release.

**Pull request merged**
