### PR TITLE
[JENKINS-66205] Correctly set SMTP port

### PR DESCRIPTION
**Pull request by wwuck**
- Set the SMTP port correctly using the suggested fix from https://issues.jenkins.io/browse/JENKINS-66205

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by wwuck** [comment]
@basil Does this need any changes/additions to tests?  My Java skills are a bit lacking here, so assistance/guidance on that would be welcomed.

**Comment by basil** [comment]
Thanks for the PR! I left some instructions about how to test the incremental build in [JENKINS-66205 (comment)](https://issues.jenkins.io/browse/JENKINS-66205?focusedCommentId=411757&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-411757). Ideally the reporter of the issue can verify that the incremental build works.

As for the tests, it would be good to add new tests for this, but given the nature of the issue that's discussed in the linked ticket, I can understand that it may not be straightforward. There are no existing tests of this kind in Email Extension. We do have plugins that do sophisticated integration testing using [Testcontainers](https://www.testcontainers.org/) (e.g. [Jenkins LDAP Plugin](https://plugins.jenkins.io/ldap/)), but writing such tests is a more significant undertaking. If the reporter of the issue can verify that the incremental build works, that would certainly be good enough to merge this PR.

**Comment by wwuck** [comment]
Thanks.  I did a quick test here with the incremental build and it still works for my jenkins sending to google smtp relay.

**Comment by basil** [comment]
Released in [2.84](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.84).

**Pull request merged**
