### PR TITLE
add backwards compatible symbol

### PR DESCRIPTION
**Pull request by jetersen**
as suggested by @jglick in https://github.com/jenkinsci/email-ext-plugin/pull/212#discussion_r551444817

### CODE REVIEW

**Review by jtnord — APPROVED** [review]

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Comment by oleg-nenashev** [comment]
Hi @basil . Would it be possible to release it?

**Comment by basil** [comment]
Released in [2.81](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.81).

**Comment by oleg-nenashev** [comment]
Thank you!

**Pull request merged**
