### PR TITLE
private readResolve not honored by subtypes

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Review by slide — APPROVED** [review]

**Comment by jglick** [comment]
Was not able to reproduce `ExtendedEmailPublisherTest` failures from second build locally. `Mailbox` is empty? I noticed

```
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at hudson.plugins.emailext.ExtendedEmailPublisherTest$SleepOnceBuilder.perform(ExtendedEmailPublisherTest.java:1307)
	at …
```

which might be related; Java unfortunately does not record a stack trace of the thread calling `Thread.interrupt`.

**Comment by jglick** [comment]
Possibly a flake; as of https://github.com/jenkinsci/plugin-pom/commit/45699826ecef116ffd46cbd601160f6af6603b36 these are no longer retried in CI.

**Comment by slide** [comment]
I restarted the build.

**Comment by jglick** [comment]
Now get some of the same failures, but not all of them.

**Comment by slide** [comment]
Thanks for improving this!

**Comment by MRamonLeon** [comment]
@basil, @davidvanlaatum could you release these changes please?

**Comment by basil** [comment]
I'll try to get a release of this out sometime this week.

**Comment by basil** [comment]
Released in [2.78](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.78).

**Pull request merged**
