### PR TITLE
bump bom

### PR DESCRIPTION
**Pull request by jetersen**
unblocking https://github.com/jenkinsci/bom/pull/1275

needs a `2.89.x` branch

@jglick noticed you had write permission, can I have a branch, please 😊

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jetersen** [comment]
Should revert e108d5 once we have a `2.89.x` branch

**Comment by jglick** [comment]
https://github.com/jenkinsci/email-ext-plugin/commits/2.89.x

**Review by jglick — APPROVED** [review]

**Review by basil — APPROVED** [review]
Thanks for the PR! Give me the word and I will do a release.

**Comment by jetersen** [comment]
@basil still waiting for incremental. Hopefully it works, but I have my doubts.

I may need to break a chain in between mina-sshd-api -> ssh-credentials for bom bumps... :)

**Comment by jetersen** [comment]
@basil all green testing locally for `bom` `2.319.x` line

**Comment by jetersen** [comment]
@basil :shipit: Confirmed to work in https://github.com/jenkinsci/bom/pull/1275 latest build is all green!

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Comment by basil** [comment]
https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.89.1

**Pull request merged**
