### PR TITLE
update jsoup from 1.9.1 to 1.12.1

### PR DESCRIPTION
**Pull request by based2**

### CODE REVIEW

**Comment by slide** [comment]
No description of a reason for this change...not going to accept a PR with no info or reasoning.

**Comment by based2** [comment]
https://github.com/jhy/jsoup/blob/master/CHANGES
1.12.1 :2019-May12
=> bugfixes
1.9.1: 2016-Apr-16

**Comment by slide** [comment]
For what bugs that are affecting email-ext?

**Comment by based2** [comment]
no bug found, just an update

**Pull request closed without merging**
